/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRiesgosRouteImport } from './routes/_authenticated/riesgos'
import { Route as AuthenticatedMissionControlRouteImport } from './routes/_authenticated/mission-control'
import { Route as AuthenticatedEsperandoRouteImport } from './routes/_authenticated/esperando'
import { Route as AuthenticatedEnviadosRouteImport } from './routes/_authenticated/enviados'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBandejaRouteImport } from './routes/_authenticated/bandeja'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedQuotesIndexRouteImport } from './routes/_authenticated/quotes.index'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices.$id'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRiesgosRoute = AuthenticatedRiesgosRouteImport.update({
  id: '/riesgos',
  path: '/riesgos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMissionControlRoute =
  AuthenticatedMissionControlRouteImport.update({
    id: '/mission-control',
    path: '/mission-control',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEsperandoRoute = AuthenticatedEsperandoRouteImport.update({
  id: '/esperando',
  path: '/esperando',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEnviadosRoute = AuthenticatedEnviadosRouteImport.update({
  id: '/enviados',
  path: '/enviados',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBandejaRoute = AuthenticatedBandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuotesIndexRoute =
  AuthenticatedQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/bandeja': typeof AuthenticatedBandejaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/enviados': typeof AuthenticatedEnviadosRoute
  '/esperando': typeof AuthenticatedEsperandoRoute
  '/mission-control': typeof AuthenticatedMissionControlRoute
  '/riesgos': typeof AuthenticatedRiesgosRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/quotes/': typeof AuthenticatedQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/bandeja': typeof AuthenticatedBandejaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/enviados': typeof AuthenticatedEnviadosRoute
  '/esperando': typeof AuthenticatedEsperandoRoute
  '/mission-control': typeof AuthenticatedMissionControlRoute
  '/riesgos': typeof AuthenticatedRiesgosRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/bandeja': typeof AuthenticatedBandejaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/enviados': typeof AuthenticatedEnviadosRoute
  '/_authenticated/esperando': typeof AuthenticatedEsperandoRoute
  '/_authenticated/mission-control': typeof AuthenticatedMissionControlRoute
  '/_authenticated/riesgos': typeof AuthenticatedRiesgosRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/quotes/': typeof AuthenticatedQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/agenda'
    | '/bandeja'
    | '/dashboard'
    | '/documentos'
    | '/enviados'
    | '/esperando'
    | '/mission-control'
    | '/riesgos'
    | '/settings'
    | '/clientes/$id'
    | '/invoices/$id'
    | '/clientes/'
    | '/invoices/'
    | '/leads/'
    | '/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/agenda'
    | '/bandeja'
    | '/dashboard'
    | '/documentos'
    | '/enviados'
    | '/esperando'
    | '/mission-control'
    | '/riesgos'
    | '/settings'
    | '/clientes/$id'
    | '/invoices/$id'
    | '/clientes'
    | '/invoices'
    | '/leads'
    | '/quotes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/agenda'
    | '/_authenticated/bandeja'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/enviados'
    | '/_authenticated/esperando'
    | '/_authenticated/mission-control'
    | '/_authenticated/riesgos'
    | '/_authenticated/settings'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/clientes/'
    | '/_authenticated/invoices/'
    | '/_authenticated/leads/'
    | '/_authenticated/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/riesgos': {
      id: '/_authenticated/riesgos'
      path: '/riesgos'
      fullPath: '/riesgos'
      preLoaderRoute: typeof AuthenticatedRiesgosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mission-control': {
      id: '/_authenticated/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof AuthenticatedMissionControlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/esperando': {
      id: '/_authenticated/esperando'
      path: '/esperando'
      fullPath: '/esperando'
      preLoaderRoute: typeof AuthenticatedEsperandoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/enviados': {
      id: '/_authenticated/enviados'
      path: '/enviados'
      fullPath: '/enviados'
      preLoaderRoute: typeof AuthenticatedEnviadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bandeja': {
      id: '/_authenticated/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof AuthenticatedBandejaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotes/': {
      id: '/_authenticated/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AuthenticatedQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedBandejaRoute: typeof AuthenticatedBandejaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEnviadosRoute: typeof AuthenticatedEnviadosRoute
  AuthenticatedEsperandoRoute: typeof AuthenticatedEsperandoRoute
  AuthenticatedMissionControlRoute: typeof AuthenticatedMissionControlRoute
  AuthenticatedRiesgosRoute: typeof AuthenticatedRiesgosRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedQuotesIndexRoute: typeof AuthenticatedQuotesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedBandejaRoute: AuthenticatedBandejaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEnviadosRoute: AuthenticatedEnviadosRoute,
  AuthenticatedEsperandoRoute: AuthenticatedEsperandoRoute,
  AuthenticatedMissionControlRoute: AuthenticatedMissionControlRoute,
  AuthenticatedRiesgosRoute: AuthenticatedRiesgosRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedQuotesIndexRoute: AuthenticatedQuotesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
