/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiesgosRouteImport } from './routes/riesgos'
import { Route as EsperandoRouteImport } from './routes/esperando'
import { Route as EnviadosRouteImport } from './routes/enviados'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as BandejaRouteImport } from './routes/bandeja'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const RiesgosRoute = RiesgosRouteImport.update({
  id: '/riesgos',
  path: '/riesgos',
  getParentRoute: () => rootRouteImport,
} as any)
const EsperandoRoute = EsperandoRouteImport.update({
  id: '/esperando',
  path: '/esperando',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviadosRoute = EnviadosRouteImport.update({
  id: '/enviados',
  path: '/enviados',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaRoute = BandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ajustes': typeof AjustesRoute
  '/bandeja': typeof BandejaRoute
  '/documentos': typeof DocumentosRoute
  '/enviados': typeof EnviadosRoute
  '/esperando': typeof EsperandoRoute
  '/riesgos': typeof RiesgosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ajustes': typeof AjustesRoute
  '/bandeja': typeof BandejaRoute
  '/documentos': typeof DocumentosRoute
  '/enviados': typeof EnviadosRoute
  '/esperando': typeof EsperandoRoute
  '/riesgos': typeof RiesgosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ajustes': typeof AjustesRoute
  '/bandeja': typeof BandejaRoute
  '/documentos': typeof DocumentosRoute
  '/enviados': typeof EnviadosRoute
  '/esperando': typeof EsperandoRoute
  '/riesgos': typeof RiesgosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/ajustes'
    | '/bandeja'
    | '/documentos'
    | '/enviados'
    | '/esperando'
    | '/riesgos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/ajustes'
    | '/bandeja'
    | '/documentos'
    | '/enviados'
    | '/esperando'
    | '/riesgos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/ajustes'
    | '/bandeja'
    | '/documentos'
    | '/enviados'
    | '/esperando'
    | '/riesgos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AjustesRoute: typeof AjustesRoute
  BandejaRoute: typeof BandejaRoute
  DocumentosRoute: typeof DocumentosRoute
  EnviadosRoute: typeof EnviadosRoute
  EsperandoRoute: typeof EsperandoRoute
  RiesgosRoute: typeof RiesgosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/riesgos': {
      id: '/riesgos'
      path: '/riesgos'
      fullPath: '/riesgos'
      preLoaderRoute: typeof RiesgosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esperando': {
      id: '/esperando'
      path: '/esperando'
      fullPath: '/esperando'
      preLoaderRoute: typeof EsperandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviados': {
      id: '/enviados'
      path: '/enviados'
      fullPath: '/enviados'
      preLoaderRoute: typeof EnviadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja': {
      id: '/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof BandejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AjustesRoute: AjustesRoute,
  BandejaRoute: BandejaRoute,
  DocumentosRoute: DocumentosRoute,
  EnviadosRoute: EnviadosRoute,
  EsperandoRoute: EsperandoRoute,
  RiesgosRoute: RiesgosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
